version: '3.8'

services:
  data-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-bridge
    ports:
      - "8765:8765"
    networks:
      - sos-network

  core-engine:
    build:
      context: .
      dockerfile: Dockerfile.core-engine
    container_name: core-engine
    environment:
      - WEBSOCKET_URI=ws://data-bridge:8765
    networks:
      - sos-network
    depends_on:
      - data-bridge

networks:
  sos-network:
    driver: bridge
